// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zkmkuqktbkfqkjclnnth.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InprbWt1cWt0YmtmcWtqY2xubnRoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5Njg5NDcsImV4cCI6MjA2NDU0NDk0N30.yyQqZdBehlkSmm4xlPwvywm3Q07-RhSS4rqpTvj76fU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);